name: torch-env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2024.12.31=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=1.0.3=h7f8727e_2
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1w=h7f8727e_0
  - pip=25.0=py310h06a4308_0
  - python=3.10.4=h12debd9_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=75.8.0=py310h06a4308_0
  - sqlite=3.38.5=hc218d9a_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2025a=h04d1e81_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - pip
pip:
  annotated-types==0.7.0
  certifi==2025.1.31
  charset-normalizer==3.4.1
  click==8.1.8
  contourpy==1.3.1
  cycler==0.12.1
  docker-pycreds==0.4.0
  filelock==3.17.0
  fonttools==4.56.0
  fsspec==2025.2.0
  gitdb==4.0.12
  GitPython==3.1.44
  h5py==3.13.0
  idna==3.10
  Jinja2==3.1.5
  kiwisolver==1.4.8
  lightning-utilities==0.12.0
  MarkupSafe==3.0.2
  matplotlib==3.10.0
  mpmath==1.3.0
  networkx==3.4.2
  numpy==2.2.3
  nvidia-cublas-cu12==12.4.5.8
  nvidia-cuda-cupti-cu12==12.4.127
  nvidia-cuda-nvrtc-cu12==12.4.127
  nvidia-cuda-runtime-cu12==12.4.127
  nvidia-cudnn-cu12==9.1.0.70
  nvidia-cufft-cu12==11.2.1.3
  nvidia-curand-cu12==10.3.5.147
  nvidia-cusolver-cu12==11.6.1.9
  nvidia-cusparse-cu12==12.3.1.170
  nvidia-cusparselt-cu12==0.6.2
  nvidia-nccl-cu12==2.21.5
  nvidia-nvjitlink-cu12==12.4.127
  nvidia-nvtx-cu12==12.4.127
  packaging==24.2
  pandas==2.2.3
  pillow==11.1.0
  platformdirs==4.3.6
  protobuf==5.29.3
  psutil==7.0.0
  pyaml==25.1.0
  pydantic==2.10.6
  pydantic_core==2.27.2
  pyparsing==3.2.1
  python-dateutil==2.9.0.post0
  pytz==2025.1
  PyYAML==6.0.2
  requests==2.32.3
  sentry-sdk==2.22.0
  setproctitle==1.3.5
  six==1.17.0
  smmap==5.0.2
  sympy==1.13.1
  tdqm==0.0.1
  torch==2.6.0
  torchmetrics==1.6.1
  torchvision==0.21.0
  tqdm==4.67.1
  triton==3.2.0
  typing_extensions==4.12.2
  tzdata==2025.1
  urllib3==2.3.0
  wandb==0.19.7
  onnx==1.17.0

